load("@crates//:defs.bzl", "all_crate_deps", "aliases")
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(default_visibility = ["//crates:__subpackages__"])

exports_files(["Cargo.toml"], visibility = ["//visibility:public"])

rust_library(
    name = "ocr",
    srcs = glob(["src/**/*.rs"]),
    compile_data = [
        "//models:manifest.json",
        "//third_party/licenses:downloads.json",
        "//third_party/onnxruntime:manifest.json",
    ],
    crate_name = "into_markdown_ocr",
    edition = "2024",
    deps = ["//crates/core"] + all_crate_deps(normal = True),
    proc_macro_deps = all_crate_deps(proc_macro = True),
)

rust_test(
    name = "ocr_test",
    crate = ":ocr",
    aliases = aliases(normal_dev = True, proc_macro_dev = True),
    compile_data = [
        "//models:manifest.json",
        "//third_party/licenses:downloads.json",
        "//third_party/onnxruntime:manifest.json",
    ],
    edition = "2024",
    deps = ["//crates/core"] + all_crate_deps(normal_dev = True),
    proc_macro_deps = all_crate_deps(proc_macro_dev = True),
)
