[package]
name = "into-markdown-converters"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
chardetng.workspace = true
encoding_rs.workspace = true
into-markdown-core = { path = "../core" }
pulldown-cmark.workspace = true
quick-xml.workspace = true
serde_json.workspace = true
zip.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[target.'cfg(windows)'.dependencies]
winapi-util.workspace = true

[dev-dependencies]
into-markdown-render-markdown = { path = "../render-markdown" }

[lints]
workspace = true
