load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(default_visibility = ["//crates:__subpackages__"])

exports_files(["BUILD.bazel", "Cargo.toml"], visibility = ["//visibility:public"])

rust_library(
    name = "engine",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "into_markdown_engine",
    edition = "2024",
    deps = [
        "//crates/core",
        "@crates//:base64",
        "@crates//:getrandom",
        "@crates//:rustix",
        "@crates//:serde",
        "@crates//:serde_json",
        "@crates//:sha2",
        "@crates//:winapi-util",
    ] + select({
        "@platforms//os:windows": ["//crates/process-plugin"],
        "//conditions:default": [],
    }),
)

rust_test(
    name = "engine_test",
    crate = ":engine",
    edition = "2024",
    deps = [
        "//crates/core",
        "@crates//:base64",
        "@crates//:getrandom",
        "@crates//:rustix",
        "@crates//:serde",
        "@crates//:serde_json",
        "@crates//:sha2",
        "@crates//:tempfile",
    ] + select({
        "@platforms//os:windows": ["//crates/process-plugin"],
        "//conditions:default": [],
    }),
)
