import { chmod, cp, mkdir, mkdtemp, readdir, rename, rm, stat } from "node:fs/promises";
import { resolve } from "node:path";

const workspace = process.env.BUILD_WORKSPACE_DIRECTORY;
if (!workspace) throw new Error("asset update must run through bazel run");

const generated = resolve(import.meta.dirname, "generated_assets");
const destination = resolve(workspace, "web/console/dist");
const parent = resolve(workspace, "web/console");
if (destination !== resolve(workspace, "web", "console", "dist")) {
  throw new Error("refusing to update an unexpected asset directory");
}

await mkdir(parent, { recursive: true });
const temporary = await mkdtemp(resolve(parent, ".dist-update-"));
const backup = resolve(parent, ".dist-backup");
let previousMoved = false;

async function makeWritable(path) {
  const info = await stat(path).catch(() => null);
  if (!info) return;
  if (info.isDirectory()) {
    await chmod(path, 0o755);
    for (const entry of await readdir(path)) await makeWritable(resolve(path, entry));
  } else {
    await chmod(path, 0o644);
  }
}

try {
  await cp(generated, temporary, { recursive: true, force: true, dereference: true });
  await makeWritable(temporary);
  await makeWritable(backup);
  await rm(backup, { recursive: true, force: true });
  if (await stat(destination).then(() => true, () => false)) {
    await rename(destination, backup);
    previousMoved = true;
  }
  await rename(temporary, destination);
  await makeWritable(backup);
  await rm(backup, { recursive: true, force: true });
} catch (error) {
  await makeWritable(temporary);
  await rm(temporary, { recursive: true, force: true });
  if (previousMoved && !(await stat(destination).then(() => true, () => false))) {
    await rename(backup, destination);
  }
  throw error;
}
process.stdout.write("updated checked-in console assets from Bazel-generated bytes\n");
