//! Command-line entry point for the descriptor-relative asset updater.

use std::env;
use std::path::PathBuf;
use std::process::ExitCode;

fn main() -> ExitCode {
    let mut arguments = env::args_os().skip(1);
    let workspace = arguments.next().map(PathBuf::from);
    let generated = arguments.next().map(PathBuf::from);
    if workspace.is_none() || generated.is_none() || arguments.next().is_some() {
        eprintln!("usage: asset-updater <workspace> <generated-assets>");
        return ExitCode::from(2);
    }
    match asset_update::update_assets(&workspace.unwrap(), &generated.unwrap()) {
        Ok(()) => {
            println!("updated checked-in console assets from Bazel-generated bytes");
            ExitCode::SUCCESS
        }
        Err(error) => {
            eprintln!("{error}");
            ExitCode::FAILURE
        }
    }
}
