[package]
name = "into-markdown-pdfium"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
libloading.workspace = true
libc.workspace = true
object.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
thiserror.workspace = true

[lints.rust]
missing_docs = "warn"

[lints.clippy]
all = "warn"
pedantic = "warn"
