[package]
name = "into-markdown-asr"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
into-markdown-core = { path = "../core" }
into-markdown-ffmpeg = { path = "../ffmpeg" }
into-markdown-ocr = { path = "../ocr" }
whisper-rs.workspace = true

[dev-dependencies]
futures.workspace = true
tempfile.workspace = true

[lints]
workspace = true
